name: "mace_finetuning"
model: "MACE"
foundation_model: "mace-omat-0-small.model"
stress_weight: 0.0
forces_weight: 0.0
energy_weight: 1.0
multiheads_finetuning: False
model_dir: "MACE_models_Omat"
log_dir: "MACE_models_Omat"
checkpoints_dir: "MACE_models_Omat"
results_dir: "MACE_models_Omat"
train_file: "../datasets/tmQM_X1_split_05112025/tmQM_X1_train.xyz"
valid_file: "../datasets/tmQM_X1_split_05112025/tmQM_X1_val.xyz"
test_file: "../datasets/tmQM_X1_split_05112025/tmQM_X1_test.xyz"
energy_key: "REF_energy"
E0s: average 
device: cuda
batch_size: 16
valid_batch_size: 16
max_num_epochs: 100
swa: False
seed: 345
